"""init

Revision ID: ca290083de80
Revises: 
Create Date: 2026-01-30 00:25:29.180623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca290083de80'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accountflowgroup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='accountflowgroup_pkey')
    )
    op.create_table('currencytype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='currencytype_pkey')
    )
    op.create_table('flowtype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='flowtype_pkey')
    )
    op.create_table('holetype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='holetype_pkey')
    )
    op.create_table('theholelevel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('level', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='theholelevel_pkey')
    )
    op.create_table('tracetype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='tracetype_pkey')
    )
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency_type', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('max_debt_capacity', sa.Double(precision=53), nullable=True),
    sa.Column('soft_limit', sa.Double(precision=53), nullable=True),
    sa.Column('logic_account', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['currency_type'], ['currencytype.id'], name='account_currency_type_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['logic_account'], ['account.id'], name='account_logic_account_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='account_pkey')
    )
    op.create_table('actiontype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('flow_type', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['flow_type'], ['flowtype.id'], name='actiontype_flow_type_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='actiontype_pkey')
    )
    op.create_table('fxexchangecontrolrate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_currency', sa.Integer(), nullable=False),
    sa.Column('to_currency', sa.Integer(), nullable=False),
    sa.Column('currency_rate', sa.Double(precision=53), nullable=True),
    sa.ForeignKeyConstraint(['from_currency'], ['currencytype.id'], name='fxexchangecontrolrate_from_currency_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_currency'], ['currencytype.id'], name='fxexchangecontrolrate_to_currency_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='fxexchangecontrolrate_pkey')
    )
    op.create_table('account_accountflowgroup',
    sa.Column('account', sa.Integer(), nullable=False),
    sa.Column('accountflowgroup', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account'], ['account.id'], name='account_accountflowgroup_account_fkey'),
    sa.ForeignKeyConstraint(['accountflowgroup'], ['accountflowgroup.id'], name='account_accountflowgroup_accountflowgroup_fkey'),
    sa.PrimaryKeyConstraint('account', 'accountflowgroup', name='account_accountflowgroup_pkey')
    )
    op.create_table('hole',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('the_hole_level', sa.Integer(), nullable=False),
    sa.Column('currency_type', sa.Integer(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('account', sa.Integer(), nullable=False),
    sa.Column('hole_type', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Double(precision=53), nullable=True),
    sa.Column('is_currency_locked', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('require_physical_account', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['account'], ['account.id'], name='hole_account_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['currency_type'], ['currencytype.id'], name='hole_currency_type_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hole_type'], ['holetype.id'], name='hole_hole_type_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['the_hole_level'], ['theholelevel.id'], name='hole_the_hole_level_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='hole_pkey')
    )
    op.create_table('holetrace',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_account', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.Integer(), nullable=False),
    sa.Column('currency_type', sa.Integer(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('trace_type', sa.Integer(), nullable=False),
    sa.Column('execute_at_fx_rate', sa.Double(precision=53), nullable=True),
    sa.Column('realtime_fx_rate', sa.Double(precision=53), nullable=True),
    sa.Column('from_currency', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Double(precision=53), nullable=True),
    sa.ForeignKeyConstraint(['action_type'], ['actiontype.id'], name='holetrace_action_type_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['currency_type'], ['currencytype.id'], name='holetrace_currency_type_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_currency'], ['currencytype.id'], name='holetrace_from_currency_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_account'], ['account.id'], name='holetrace_source_account_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trace_type'], ['tracetype.id'], name='holetrace_trace_type_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='holetrace_pkey')
    )
    op.create_table('hole_holetrace',
    sa.Column('hole', sa.Uuid(), nullable=False),
    sa.Column('holetrace', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hole'], ['hole.id'], name='hole_holetrace_hole_fkey'),
    sa.ForeignKeyConstraint(['holetrace'], ['holetrace.id'], name='hole_holetrace_holetrace_fkey'),
    sa.PrimaryKeyConstraint('hole', 'holetrace', name='hole_holetrace_pkey')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hole_holetrace')
    op.drop_table('holetrace')
    op.drop_table('hole')
    op.drop_table('account_accountflowgroup')
    op.drop_table('fxexchangecontrolrate')
    op.drop_table('actiontype')
    op.drop_table('account')
    op.drop_table('tracetype')
    op.drop_table('theholelevel')
    op.drop_table('holetype')
    op.drop_table('flowtype')
    op.drop_table('currencytype')
    op.drop_table('accountflowgroup')
    # ### end Alembic commands ###
