"""sync_schema_1769522623

Revision ID: 33c790f18d4d
Revises: 4a5f2477ee76
Create Date: 2026-01-27 23:03:43.273825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33c790f18d4d'
down_revision: Union[str, Sequence[str], None] = '4a5f2477ee76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
