"""sync_schema_1769521387

Revision ID: 33e8e7542a32
Revises: d59341295618
Create Date: 2026-01-27 22:43:07.400826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33e8e7542a32'
down_revision: Union[str, Sequence[str], None] = 'd59341295618'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('warranty_info', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'warranty_info')
    # ### end Alembic commands ###
