"""sync_schema_1769519827

Revision ID: 6299772da6b3
Revises: b8a5c44cd687
Create Date: 2026-01-27 22:17:07.821501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6299772da6b3'
down_revision: Union[str, Sequence[str], None] = 'b8a5c44cd687'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('parent_location_id', sa.Integer(), nullable=True, comment='Self-referencing for hierarchy'),
    sa.ForeignKeyConstraint(['parent_location_id'], ['locations.id'], name='locations_parent_location_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='locations_pkey')
    )
    op.create_table('assets',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('serial_number', sa.String(), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('specifications', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Flexible asset specs'),
    sa.Column('status', sa.String(), nullable=True, comment='active, repair, retired'),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name='assets_location_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='assets_pkey'),
    sa.UniqueConstraint('serial_number', name='assets_serial_number_key')
    )
    op.create_table('asset_assignments',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('returned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name='asset_assignments_asset_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='asset_assignments_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='asset_assignments_pkey')
    )
    op.create_table('maintenance_logs',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('technician_name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('service_date', sa.Date(), nullable=True),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name='maintenance_logs_asset_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='maintenance_logs_pkey')
    )
    op.drop_table('follows')
    op.drop_table('posts')
    op.drop_table('role_info')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_info',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('role_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('role_info_pkey')),
    sa.UniqueConstraint('role_name', name=op.f('role_info_role_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('posts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('body', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('posts_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('posts_pkey'))
    )
    op.create_table('follows',
    sa.Column('following_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('followed_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['followed_user_id'], ['users.id'], name=op.f('follows_followed_user_id_fkey')),
    sa.ForeignKeyConstraint(['following_user_id'], ['users.id'], name=op.f('follows_following_user_id_fkey')),
    sa.PrimaryKeyConstraint('following_user_id', 'followed_user_id', name=op.f('follows_pkey'))
    )
    op.drop_table('maintenance_logs')
    op.drop_table('asset_assignments')
    op.drop_table('assets')
    op.drop_table('locations')
    # ### end Alembic commands ###
