"""sync_schema_1769521402

Revision ID: 70cdbcfa643f
Revises: e76d8cdaf03a
Create Date: 2026-01-27 22:43:22.999857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70cdbcfa643f'
down_revision: Union[str, Sequence[str], None] = 'e76d8cdaf03a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
