"""sync_schema_1769522890

Revision ID: 74a300e4627a
Revises: c2ee2036869e
Create Date: 2026-01-27 23:08:11.127894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74a300e4627a'
down_revision: Union[str, Sequence[str], None] = 'c2ee2036869e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('assets_serial_number_key'), 'assets', type_='unique')
    op.drop_column('assets', 'serial_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('serial_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('assets_serial_number_key'), 'assets', ['serial_number'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
