"""sync_schema_1769519430

Revision ID: b8a5c44cd687
Revises: 278ab9851717
Create Date: 2026-01-27 22:10:30.588317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8a5c44cd687'
down_revision: Union[str, Sequence[str], None] = '278ab9851717'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='role_info_pkey'),
    sa.UniqueConstraint('role_name', name='role_info_role_name_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('role_info')
    # ### end Alembic commands ###
