"""sync_schema_1769523406

Revision ID: c5962f22c16f
Revises: 7f061b58607f
Create Date: 2026-01-27 23:16:46.900970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c5962f22c16f'
down_revision: Union[str, Sequence[str], None] = '7f061b58607f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accountflowgroup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='accountflowgroup_pkey')
    )
    op.create_table('currencytype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='currencytype_pkey')
    )
    op.create_table('flowtype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='flowtype_pkey')
    )
    op.create_table('holetype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='holetype_pkey')
    )
    op.create_table('theholelevel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('level', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='theholelevel_pkey')
    )
    op.create_table('tracetype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='tracetype_pkey')
    )
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency_type', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('max_debt_capacity', sa.Double(precision=53), nullable=True),
    sa.Column('soft_limit', sa.Double(precision=53), nullable=True),
    sa.Column('logic_account', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['currency_type'], ['currencytype.id'], name='account_currency_type_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['logic_account'], ['account.id'], name='account_logic_account_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='account_pkey')
    )
    op.create_table('actiontype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('flow_type', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['flow_type'], ['flowtype.id'], name='actiontype_flow_type_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='actiontype_pkey')
    )
    op.create_table('fxexchangecontrolrate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_currency', sa.Integer(), nullable=False),
    sa.Column('to_currency', sa.Integer(), nullable=False),
    sa.Column('currency_rate', sa.Double(precision=53), nullable=True),
    sa.ForeignKeyConstraint(['from_currency'], ['currencytype.id'], name='fxexchangecontrolrate_from_currency_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_currency'], ['currencytype.id'], name='fxexchangecontrolrate_to_currency_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='fxexchangecontrolrate_pkey')
    )
    op.create_table('account_accountflowgroup',
    sa.Column('account', sa.Integer(), nullable=False),
    sa.Column('accountflowgroup', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account'], ['account.id'], name='account_accountflowgroup_account_fkey'),
    sa.ForeignKeyConstraint(['accountflowgroup'], ['accountflowgroup.id'], name='account_accountflowgroup_accountflowgroup_fkey'),
    sa.PrimaryKeyConstraint('account', 'accountflowgroup', name='account_accountflowgroup_pkey')
    )
    op.create_table('hole',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('the_hole_level', sa.Integer(), nullable=False),
    sa.Column('currency_type', sa.Integer(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('account', sa.Integer(), nullable=False),
    sa.Column('hole_type', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Double(precision=53), nullable=True),
    sa.Column('is_currency_locked', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('require_physical_account', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['account'], ['account.id'], name='hole_account_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['currency_type'], ['currencytype.id'], name='hole_currency_type_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hole_type'], ['holetype.id'], name='hole_hole_type_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['the_hole_level'], ['theholelevel.id'], name='hole_the_hole_level_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='hole_pkey')
    )
    op.create_table('holetrace',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_account', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.Integer(), nullable=False),
    sa.Column('currency_type', sa.Integer(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('trace_type', sa.Integer(), nullable=False),
    sa.Column('execute_at_fx_rate', sa.Double(precision=53), nullable=True),
    sa.Column('realtime_fx_rate', sa.Double(precision=53), nullable=True),
    sa.Column('from_currency', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Double(precision=53), nullable=True),
    sa.ForeignKeyConstraint(['action_type'], ['actiontype.id'], name='holetrace_action_type_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['currency_type'], ['currencytype.id'], name='holetrace_currency_type_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_currency'], ['currencytype.id'], name='holetrace_from_currency_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_account'], ['account.id'], name='holetrace_source_account_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trace_type'], ['tracetype.id'], name='holetrace_trace_type_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='holetrace_pkey')
    )
    op.create_table('hole_holetrace',
    sa.Column('hole', sa.Uuid(), nullable=False),
    sa.Column('holetrace', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hole'], ['hole.id'], name='hole_holetrace_hole_fkey'),
    sa.ForeignKeyConstraint(['holetrace'], ['holetrace.id'], name='hole_holetrace_holetrace_fkey'),
    sa.PrimaryKeyConstraint('hole', 'holetrace', name='hole_holetrace_pkey')
    )
    op.drop_table('maintenance_logs')
    op.drop_table('asset_assignments')
    op.drop_table('assets')
    op.drop_table('users')
    op.drop_table('locations')
    op.drop_table('dbml_test_table')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dbml_test_table',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('test_column', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('dbml_test_table_pkey'))
    )
    op.create_table('assets',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('purchase_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('cost', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('specifications', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Flexible asset specs'),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True, comment='active, repair, retired'),
    sa.Column('location_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('assets_location_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('assets_pkey'))
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_table('locations',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('parent_location_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='Self-referencing for hierarchy'),
    sa.ForeignKeyConstraint(['parent_location_id'], ['locations.id'], name=op.f('locations_parent_location_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('locations_pkey'))
    )
    op.create_table('asset_assignments',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('assigned_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('returned_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('asset_assignments_asset_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('asset_assignments_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('asset_assignments_pkey'))
    )
    op.create_table('maintenance_logs',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('technician_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('service_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('cost', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('maintenance_logs_asset_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('maintenance_logs_pkey'))
    )
    op.drop_table('hole_holetrace')
    op.drop_table('holetrace')
    op.drop_table('hole')
    op.drop_table('account_accountflowgroup')
    op.drop_table('fxexchangecontrolrate')
    op.drop_table('actiontype')
    op.drop_table('account')
    op.drop_table('tracetype')
    op.drop_table('theholelevel')
    op.drop_table('holetype')
    op.drop_table('flowtype')
    op.drop_table('currencytype')
    op.drop_table('accountflowgroup')
    # ### end Alembic commands ###
