"""sync_schema_1769523186

Revision ID: fe28deccb8e6
Revises: 74a300e4627a
Create Date: 2026-01-27 23:13:06.819477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe28deccb8e6'
down_revision: Union[str, Sequence[str], None] = '74a300e4627a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dbml_test_table',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), nullable=False),
    sa.Column('test_column', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='dbml_test_table_pkey')
    )
    op.drop_column('assets', 'warranty_info')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('warranty_info', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table('dbml_test_table')
    # ### end Alembic commands ###
